steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/dashboard-501105/cloud-run-source-deploy/ecommerce-dashboard', './dashboard']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/dashboard-501105/cloud-run-source-deploy/ecommerce-dashboard']

  - name: 'gcr.io/google-cloud-sdk/slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecommerce-dashboard'
      - '--image=asia-southeast2-docker.pkg.dev/dashboard-501105/cloud-run-source-deploy/ecommerce-dashboard'
      - '--region=asia-southeast2'
      - '--platform=managed'

images:
  - 'asia-southeast2-docker.pkg.dev/dashboard-501105/cloud-run-source-deploy/ecommerce-dashboard'
options:
  logging: CLOUD_LOGGING_ONLY
